name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ['2.7', '3.4', '3.5', '3.6', 'pypy-2.7', 'pypy-3.6']
        include:
          - python-version: '3.6'
            env:
              LANG: C
          - python-version: '2.7'
            env:
              LANG: C

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install tox tox-venv
    
    - name: Display environment
      run: env
    
    - name: Bootstrap setuptools
      run: python bootstrap.py
    
    - name: Run tests with coverage
      if: ${{ !startsWith(matrix.python-version, 'pypy') }}
      run: tox -- --cov
    
    - name: Run tests without coverage (PyPy)
      if: ${{ startsWith(matrix.python-version, 'pypy') }}
      run: tox
    
    - name: Upload coverage
      if: ${{ !startsWith(matrix.python-version, 'pypy') }}
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        export TRAVIS_JOB_NAME="Python ${{ matrix.python-version }} (LANG=${{ matrix.env.LANG || 'default' }})"
        export CODECOV_ENV=TRAVIS_JOB_NAME
        tox -e coverage,codecov || true

